image: acquia/ads-local:lando-php-7.3-nodejs-10

stages:
  - build
  - validate
  - setup_and_test
  - deploy

variables:
  APP_NAME: BLT-Project
  BLT: ./vendor/bin/blt
  SCRIPT_DIR: ./vendor/mikemadison13/blt-gitlab-pipelines/scripts/gitlab
  MYSQL_DATABASE: drupal
  MYSQL_ROOT_PASSWORD: drupal

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull-push
  paths:
    - $HOME/.npm
    - $HOME/.nvm
    - $CI_PROJECT_DIR/docroot/core
    - $CI_PROJECT_DIR/docroot/libraries
    - $CI_PROJECT_DIR/docroot/modules/contrib
    - $CI_PROJECT_DIR/docroot/themes/contrib
    - $CI_PROJECT_DIR/docroot/profiles/contrib
    - $CI_PROJECT_DIR/vendor

.global_cache:
  cache:
    <<: *global_cache
    policy: pull-push

before_script:
  - $SCRIPT_DIR/add_keys.sh

build:
  stage: build
  extends: .global_cache
  allow_failure: false
  script:
    - composer validate --no-check-all --ansi
    - composer install
    - npm install npm@latest -g

validate:
  stage: validate
  extends:
    - .global_cache
    - build
  allow_failure: false
  script:
    - $SCRIPT_DIR/validate.sh

setup_and_test:
  stage: setup_and_test
  extends:
    - .global_cache
    - build
  services:
    - mysql:5.7
  allow_failure: false
  script:
    - $SCRIPT_DIR/setup_env.sh
    - $SCRIPT_DIR/setup_app.sh
    - $SCRIPT_DIR/test.sh

deploy:
  stage: deploy
  extends:
    - .global_cache
    - build
  rules:
    - if: '$CI_MERGE_REQUEST_ID !~ /.+/'
      when: always
      allow_failure: false
  script:
    - $SCRIPT_DIR/setup_env.sh
    - $SCRIPT_DIR/deploy_branch.sh
