stages:
  - build
  - deploy

variables:
  APP_NAME: BLT-Project
  BLT: ./vendor/bin/blt
  SSH_HOST: acquia.com
  SCRIPT_DIR: ./vendor/flux423/blt-gitlab-pipelines/scripts/gitlab
  MYSQL_DATABASE: drupal
  MYSQL_ROOT_PASSWORD: root
  PHP_VERSION: "8.0"
  NODE_VERSION: "14.x"

image: devwithlando/php:$PHP_VERSION-apache-2

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull-push
  paths:
    - $HOME/.npm
    - $HOME/.nvm
    - $CI_PROJECT_DIR/docroot/core
    - $CI_PROJECT_DIR/docroot/libraries
    - $CI_PROJECT_DIR/docroot/modules/contrib
    - $CI_PROJECT_DIR/docroot/themes/contrib
    - $CI_PROJECT_DIR/docroot/profiles/contrib
    - $CI_PROJECT_DIR/vendor

.global_cache:
  cache:
    <<: *global_cache
    policy: pull-push
  only:
    variables:
      - $GITLAB_CI
      - $CI_COMMIT_SHA
      - $CI_COMMIT_REF_NAME
      - $CI_JOB_ID
      - $CI_SERVER_VERSION
      - $CI_COMMIT_BRANCH
      - $CI_MERGE_REQUEST_ID
      - $PERCY_TOKEN
      - $MYSQL_DATABASE
      - $MYSQL_ROOT_PASSWORD

before_script:
  - apt-get update -y && apt-get install openssh-client -y
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - ssh-keyscan -H -t rsa "$SSH_HOST" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - chmod 700 ~/.ssh

build:
  stage: build
  extends: .global_cache
  allow_failure: false
  services:
    - mysql:5.7
  script:
    - composer validate --no-check-all --ansi
    - composer install
    - $SCRIPT_DIR/setup_env.sh
    - $SCRIPT_DIR/validate.sh
    - $SCRIPT_DIR/setup_app.sh
    - $SCRIPT_DIR/test.sh

deploy:
  stage: deploy
  extends:
    - .global_cache
    - build
  allow_failure: false
  only:
    - $CI_MERGE_REQUEST_ID =~ ".+"
    - main
    - master
    - /^hotfix.*$/
  script:
    - $SCRIPT_DIR/deploy_artifact.sh